build_scripts/generate_settings.py
add description in generate_settings.py script
=> add doc for generate settings

.github/pull_request_template.md
=> provide clarity on the PR template

doc/api_collection_programs/mcafee_cloud_proxy/job_mcp.py, doc/api_collection_programs/proofpoint/proofpoint_pod/kafka_client.py, doc/api_collection_programs/proofpoint/proofpoint_pod/pod_logging/pp_pod_job.service
I added in API versioning capability/compatability for MCP
=> add in API versioning capability for MCP

doc/elastic_common_schema/ecs_1.9_with_custom_fields.csv
Adding in the ECS 1.9 CSV with custom fields our team uses. Please note the addition of event.recommendation. This was not a custom field in our 1.7 CSV.
=> added in ECS 1.9 with custom fields

config/processors/syslog_log_audit_checkpoint.operations.conf
I added in parsing to map fields to ECS, specifically for checkpoint incorrect password attempts.
=> include checkpoint parsing for PAM failed logins

config/processors/event_hub_log_security_azure.event_hub.conf
Add initial parsing for Azure Eventhub Security Logs.
None
N/A
=> Eventhub security parsing

config/processors/api_log_security_aws.guardduty.conf
added new field "event.severity" for aws.guardduty
NA
NA
=> added new field "event.severity" for aws.guardduty

config/processors/syslog_log_security_mcafee.net.security.mgr.conf
renamed manager, archiving and scheduler fields and removing them at end.
NA
syslog_log_security_mcafee.net.security.mgr causes elastic to reject events #31
NA
=> removing non ecs fields (issue #31)

config/enrichments/15_related_hash.conf
Added ECS 1.9 fields in related hash enrichment
N/A
N/A
=> Added ECS 1.9 fields in related hash enrichment

config/enrichments/06_url.conf
Enabled top level domain look up in URL enrichment
=> Reenabled TLD in URL enrichment

config/enrichments/11_user_agent_enrichment.conf
Added user_agent enrichment (11_user_agent_enrichment.conf)
NA
NA
=> Added user_agent enrichment

config/processors/syslog_log_security_cisco.stealthwatch.conf
There is logic added to check for when Stealthwatch sends a string "localhost" instead of an IP.
None
=> Cisco Stealthwatch: add in conditional to check for localhost string instead of ip data type

config/processors/syslog_log_security_tanium.conf
Tanium: added parsing for logs with 'not parsed' tags
NA
NA
=> Tanium: added parsing for logs with 'not parsed' tags

config/processors/syslog_log_security_symantec.endpoint.conf
=> remove irrelevant sep fields that don't apply to general use

doc/log_configurations/mcafee_web_gateway.txt
Added rule= Last rule field to the log to capture the last rule the proxy went through on the request
=> Added Last Rule

config/processors/syslog_log_security_mcafee.mwg.conf
The MWG log format is changing, with the addition of the field "rule" - so the parsing must be updated to facilitate the new log format.
https://github.com/Cargill/OpenSIEM-Logstash-Parsing/pull/66
Not an issue, but this PR details the change in the log format
=> update the MWG log schema  dissect

config/processors/syslog_log_security_tanium.conf
tanium: parsing file.path when rule.name is 'reputation malicious files'
NA
NA
=> tanium: parsing file.path when rule.name is 'reputation malicious files'

config/processors/syslog_log_security_mcafee.atd.conf
mcafee.atd: syslog new parsing header added; field casing error fixed and removed commented code and log; also removed unnecessary fields from 'remove_field'
NA
NA
=> mcafee.atd: changed syslog new parsing header, field case error fixed, and removed commented code and log

config/processors/flat_file_log_audit_riverbed.amauth.conf
=> added parsing for failed login

config/processors/syslog_log_security_tanium.conf
case changed in file.path filter and moved it out of openioc condition
NA
NA
=> Tanium: case changed in file.path filter and moved it out of openioc condition

config/processors/syslog_log_audit_tenable.nessus_scanner.conf
tenable nessus: added parsing as requested by Kartikeya
NA
NA
=> Nessus - parsed formats as requested by Kartikeya.

.github/workflows/main.yml
Syntax check PRs are failing because existing gpg servers are not always working.
Added more to try.
NA
NA
=> add 2 more gpg servers

config/processors/wef_log_audit_windows.events.conf
wef: changes in filter for event id 7036; added grokparsefailure tags
NA
NA
=> wef: changes in filter for event id 7036; added grokparsefailure tags

config/processors/syslog_log_audit_tenable.nessus_scanner.conf
We added a lower-cased and capitalized version of "T.NessusCore" in our if conditional to pick up on the log format change. Also, we added an else conditional to catch any logs without this tag.
No
No
=> Nessus scanner parsing update

config/processors/flat_file_log_audit_riverbed.amauth.conf
riverbed.amauth: copied message to tmp field and parsing it after removing the new line characters
No
NA
=> riverbed.amauth: copied message to tmp field and parsing it after removing the new line characters

config/processors/syslog_log_security_a10.waf.conf
concatenate the url.path to the 'dhost' field, and putting that all into url.full
No
NA
=> A10: concatenate the url.path to the 'dhost' field, and putting that all into url.full

config/processors/syslog_log_audit_cisco.router.conf, config/processors/syslog_log_audit_cisco.switch.conf
- Added pri parsing
- Fixed error causing field
- Fixed dissect & grok failures
No
NA
=> 400 error fix in cisco.router and cisco.switch

config/processors/event_hub_log_audit_azure.event_hub_audit.conf
=> added mapping for identity to file.group

config/processors/syslog_log_audit_tenable.nessus_scanner.conf
changed grok filter mapping ip pattern to avoid 400 error and dissectfailure4 tags resolved
No
NA
=> Nessus: changed grok filter mapping ip pattern to avoid 400 error and dissectfailure4 tags resolved

config/processors/api_log_network_oci.vcn.conf
oci_vcn: added date parsing
No
NA
=> oci_vcn: added date parsing

config/processors/api_log_network_oci.vcn.conf
added json filter to the config as the input format changed to plain
No
NA
=> oci.vcn: added json filter to the config as the input format changed to plain

config/processors/api_log_application_oci.object.conf, config/processors/api_log_security_azure.o365_dlp.conf, config/processors/api_log_security_oci.cloudguard.conf, config/processors/api_log_security_scorecard.events.conf
added processors to open repo from cgl
No
NA
=> added processors to open repo

config/processors/flat_file_log_audit_exchange.2016.msg.trkg.conf
using grok pattern instead of csv header and removed few non ecs fields
No
NA
=> exchange_2016: using grok pattern instead of csv header and removed few non ecs fields

config/processors/flat_file_log_audit_exchange.2016.msg.trkg.conf
removing 'source' field - 400 fix
No
NA
=> removing 'source' field - 400 fix

config/processors/api_log_security_azure.graph_api.conf
user.name changed to user.email; added ecs field for 'netBiosName' as host.hostname
No
NA
=> azure.graph_api: user.name changed to user.email; added ecs field for 'netBiosName' as host.hostname

config/processors/syslog_log_security_symantec.endpoint.conf
removed non ecs fields, indentation changes and date filter changes
No
NA
=> removed non ecs fields, indentation changes and date filter changes

config/processors/syslog_log_security_symantec.endpoint.conf
added updated parsing from logindexer
No
NA
=> added updated parsing from logindexer

config/processors/api_log_security_oci.cloudguard.conf
parsing enhancement - changed parsing from kv to json 
No
NA
=> oci cloudguard: parsing enhancement - changed parsing from kv to json 

doc/api_collection_programs/proofpoint/proofpoint_siem/pp_siem.py
This is a change to the proofpoint SIEM API collection program. This change removes the Kafka functions in the program and calls the kafka helper file instead.
No
=> add in updates to pp_siem.py

config/processors/syslog_log_security_sdwan.os_ubuntu.conf
- added new syslog parsing pattern
- added new logs parsing
- resolved dissect failures and grok failures
No
NA
=> Sdwan Ubuntu: added parsing for new log patterns causing dissect and grok failures

config/processors/api_log_security_azure.graph_api.conf
added gsub filter to fix json failure and added if condition to check for empty fields
No
NA
=> azure.graph_api: added gsub filter to fix json failure and added if condition to check for empty fields

config/processors/api_log_security_oci.cloudguard.conf
oci cloudguard: parsing enhancement - added parsing for 2 new fields
No
NA
=> oci cloudguard: parsing enhancement - added parsing for 2 new fields

doc/elastic_common_schema/ecs_1.9_with_custom_fields.csv
Last ECS doc update the rows did not line up
None
none
=> updated ECS formatting

doc/log_configurations/linux/README.md, doc/log_configurations/linux/rsyslog.conf
Added basic instructions for forwarding linux logs to a centralized server and configuring auditd to be able to log user activities
=> Basic instructions for linux logging

doc/log_configurations/linux/rsyslog.conf
Adding log type so relays can identify
=> add log type

config/processors/syslog_log_audit_cisco.dna.conf
revert to old cisco.dna parsing (to avoid 400 errors)
No
NA
=> revert to old dna parsing

config/processors/syslog_log_security_cisco.ise.conf
added check for host.hostname before mapping it to another field, for mat for ise_timestamp added and indentation changes
No
NA
=> added check for host.hostname before mapping it to another field, for mat for ise_timestamp added and indentation changes

config/processors/syslog_log_audit_cisco.dna.conf
added syslog parsing, new log pattern parsing enhancement and commented out event.start
No
NA
=> added syslog parsing, new log pattern parsing enhancement and commented out event.start

config/processors/syslog_log_security_guardium.db.conf
added parsing for 'alert name'
No
NA
=> guardium db: added parsing for 'alert name'

config/processors/syslog_log_security_guardium.db.conf
added date parsing for event.start and indenatation changes
No
NA
=> added date parsing for event.start and indenatation changes

config/processors/syslog_log_security_symantec.endpoint.conf
Updated Symantec Endpoint Protection to add NTP to rule.category for NTP events
Noe
none
=> fixexed ntp cat

config/processors/api_log_security_proofpoint.pod_email_gateway.conf
- added if condition to check protocol field before dissecting it 
- gsub colmodel,attrib keys - to remove [] (which are cause for fieldmapping errors) 
- removing multi slashes to avoid json parse failures
No
NA
=> proofpoint.pod_email_gateway: jsonparsefailures, fieldmapping issue fix

config/processors/syslog_log_security_tanium.conf
Added parsing for intel type reputation 
=> added repution type to tanium

GETTING_STARTED.md, README.md, build_scripts/README.md
Added two sets of quick start instructions.
Second set were also tested on macbook by replacing /usr/share/logstash/config/ with /usr/local/etc/logstash/
#5 
=> add getting started guide

.github/workflows/main.yml
Using GPG key from elastic
#77
=> use gpg key from elastic

config/enrichments/02_remove_empty_n_truncate.conf
fix for log drops due to '' in ip fields
No
NA
=> fix for log drops due to '' in ip fields
